celebrities = [
    {"name": "Cristiano Ronaldo", "country": "Portugal", "profession": "Footballer", "followers": 647},
    {"name": "Lionel Messi", "country": "Argentina", "profession": "Footballer", "followers": 504},
    {"name": "Selena Gomez", "country": "USA", "profession": "Musician and actress", "followers": 423},
    {"name": "Kylie Jenner", "country": "USA", "profession": "Media personality", "followers": 395},
    {"name": "Dwayne Johnson", "country": "USA", "profession": "Actor and wrestler", "followers": 394},
    {"name": "Ariana Grande", "country": "USA", "profession": "Musician and actress", "followers": 376},
    {"name": "Kim Kardashian", "country": "USA", "profession": "Media personality", "followers": 359},
    {"name": "Beyoncé", "country": "USA", "profession": "Musician and actress", "followers": 313},
    {"name": "Khloé Kardashian", "country": "USA", "profession": "Media personality", "followers": 305},
    {"name": "Justin Bieber", "country": "Canada", "profession": "Musician", "followers": 295},
    {"name": "Kendall Jenner", "country": "USA", "profession": "Media personality", "followers": 290},
    {"name": "Taylor Swift", "country": "USA", "profession": "Musician", "followers": 283},
    {"name": "Virat Kohli", "country": "India", "profession": "Cricketer", "followers": 270},
    {"name": "Jennifer Lopez", "country": "USA", "profession": "Musician and actress", "followers": 249},
    {"name": "Nicki Minaj", "country": "Trinidad and Tobago", "profession": "Musician", "followers": 227},
    {"name": "Neymar", "country": "Brazil", "profession": "Footballer", "followers": 227},
    {"name": "Kourtney Kardashian", "country": "USA", "profession": "Media personality", "followers": 220},
    {"name": "Miley Cyrus", "country": "USA", "profession": "Musician and actress", "followers": 213},
    {"name": "Katy Perry", "country": "USA", "profession": "Musician", "followers": 205},
    {"name": "Zendaya", "country": "USA", "profession": "Actress and singer", "followers": 180},
    {"name": "Kevin Hart", "country": "USA", "profession": "Comedian and actor", "followers": 177},
    {"name": "Cardi B", "country": "USA", "profession": "Musician and actress", "followers": 164},
    {"name": "LeBron James", "country": "USA", "profession": "Basketball player", "followers": 159},
    {"name": "Demi Lovato", "country": "USA", "profession": "Musician and actress", "followers": 154},
    {"name": "Rihanna", "country": "Barbados", "profession": "Musician", "followers": 150},
    {"name": "Chris Brown", "country": "USA", "profession": "Musician", "followers": 144},
    {"name": "Drake", "country": "Canada", "profession": "Musician", "followers": 143},
    {"name": "Ellen DeGeneres", "country": "USA", "profession": "Comedian and television host", "followers": 137},
    {"name": "Kylian Mbappé", "country": "France", "profession": "Footballer", "followers": 122},
    {"name": "Billie Eilish", "country": "USA", "profession": "Musician", "followers": 121}
]
